// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAHCDYW1Mquca4L8N8-ZWrhTtT2MgkaU',
    appId: '1:514173068988:web:03584e9fcaee66cc00d2b9',
    messagingSenderId: '514173068988',
    projectId: 'ai-hackathon-test1',
    authDomain: 'ai-hackathon-test1.firebaseapp.com',
    storageBucket: 'ai-hackathon-test1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuwjOhwCnDRvYqXBl2m97wFPm5ee5YIM',
    appId: '1:514173068988:android:37747c14d7e7fd4c00d2b9',
    messagingSenderId: '514173068988',
    projectId: 'ai-hackathon-test1',
    storageBucket: 'ai-hackathon-test1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjw__VrQVLPsfIsshUGnQVl5yiq8hwzwU',
    appId: '1:514173068988:ios:140a7b685c2e9d8500d2b9',
    messagingSenderId: '514173068988',
    projectId: 'ai-hackathon-test1',
    storageBucket: 'ai-hackathon-test1.firebasestorage.app',
    iosBundleId: 'com.example.hackathonTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjw__VrQVLPsfIsshUGnQVl5yiq8hwzwU',
    appId: '1:514173068988:ios:140a7b685c2e9d8500d2b9',
    messagingSenderId: '514173068988',
    projectId: 'ai-hackathon-test1',
    storageBucket: 'ai-hackathon-test1.firebasestorage.app',
    iosBundleId: 'com.example.hackathonTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAHCDYW1Mquca4L8N8-ZWrhTtT2MgkaU',
    appId: '1:514173068988:web:7fb51aacfd22e70c00d2b9',
    messagingSenderId: '514173068988',
    projectId: 'ai-hackathon-test1',
    authDomain: 'ai-hackathon-test1.firebaseapp.com',
    storageBucket: 'ai-hackathon-test1.firebasestorage.app',
  );
}
