steps:
  - name: "python:3.12"
    id: eval
    entrypoint: /bin/bash
    env:
      - 'PYTHONPATH=.'
    args:
      - "-c"
      - |
        pip install uv && uv pip install --system -r requirements.txt
        adk eval app/ app/simple_weather_eval_set.evalset.json --config_file_path=evaluations/test_config.json | tee eval_output.log
        if grep -q "Tests failed: [1-9][0-9]*" eval_output.log; then
          echo "Evaluation failed."
          exit 1
        fi
  - name: "python:3.12"
    id: deploy
    entrypoint: /bin/bash
    env:
      - 'PYTHONPATH=.'
    args:
      - "-c"
      - |
        pip install uv && uv pip install --system -r requirements.txt && python3 -m app.agent_engine_app --project ${PROJECT_ID} --agent-name ${_AGENT_NAME} --location ${_REGION} --requirements-file requirements.txt --extra-packages ./app

substitutions:
  _REGION: us-central1
  _AGENT_NAME: my-first-agent

logsBucket: gs://${PROJECT_ID}-sample-app-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET