name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. リポジトリのコードを取得
      - name: Check out
        uses: actions/checkout@v3

      # 2. GCP 認証 (サービスアカウント JSON を使う例)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. gcloud CLI のセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4. Cloud Run にデプロイ
      - name: Deploy genai-backend
        run: |
          # 今回はビルド時ではなく、実行時に環境変数をセットする
          # (--set-env-vars は「実行時」の環境変数指定)
          # SERVICE_ACCOUNT はチュートリアル通り
          # FLASK_PROJECT_ID は ${{ secrets.GCP_PROJECT_ID }} を割り当て

          gcloud run deploy genai-backend \
            --source ./src/genai-backend \
            --region asia-northeast1 \
            --service-account genai-backend-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --set-env-vars=FLASK_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --no-allow-unauthenticated
