name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      # (認証設定) ここで service_account_key をセット
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          # 認証確認（ここでアクティブアカウントが表示されればOK）
          echo "Check gcloud auth list"
          gcloud auth list

          # リージョン固定
          gcloud config set run/region asia-northeast1

          # デプロイ
          gcloud run deploy my-service \
            --source . \
            --platform managed \
            --allow-unauthenticated
