# .github/workflows/deploy.yml
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガーにする例

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Check out the code
        uses: actions/checkout@v3

      # 2. gcloud CLI をセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3. Cloud Runにデプロイ
      - name: Deploy to Cloud Run
        run: |
          # 必要に応じてビルドコマンドやテストをここで行う
          # 例: npm install && npm test / pip install && pytest など
          
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud run deploy my-service \
            --source . \
            --platform managed \
            --allow-unauthenticated
