name: Deploy to Cloud Run

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. リポジトリのコードを取得
      - name: Check out
        uses: actions/checkout@v3

      # 2. GCP 認証 (サービスアカウント JSON を使う例)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. gcloud CLI のセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4. Cloud Run にデプロイ
      - name: Build container image
        run: |
          gcloud builds submit \
            --region=asia-northeast1 \
            --tag=asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatbot-api-repo/chatbot-api:v1 \
            .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatbot-api \
            --image=asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chatbot-api-repo/chatbot-api:v1 \
            --region=asia-northeast1 \
            --allow-unauthenticated \
            --set-env-vars=VERTEX_AI_LOCATION=asia-northeast1,PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GENERATIVE_MODEL_NAME=gemini-pro