name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # 1. gcloud CLI のセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 2. Cloud Run デプロイ
      - name: Deploy to Cloud Run
        run: |
          # リージョンを固定で設定
          gcloud config set run/region asia-northeast1
          # ソースから Cloud Run へデプロイ
          gcloud run deploy my-service \
            --source . \
            --platform managed \
            --allow-unauthenticated
