name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v3

      # (1) Service Accountキーで認証する
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # (2) gcloud CLI をセットアップ
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # 必要に応じて、Cloud Build用に追加コンポーネントを入れる例
          install_components: cloud-build-local

      # (3) gcloud コマンドでデプロイ
      - name: Deploy to Cloud Run
        run: |
          echo "Check gcloud auth list"
          gcloud auth list

          gcloud config set run/region asia-northeast1
          gcloud run deploy ai-organizer \
            --source ./2024/genai-app-patterns/src/ai-organizer \
            --service-account ai-organizer-sa@$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com \
            --platform managed \
            --allow-unauthenticated
